### ISSUE TITLE
certbund-contact: dev-rework-notification uses enum, not available for Python 3.3

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq#20]
https://github.com/Intevation/intelmq/blob/8008aee295522854a35fa77b1ea0874e8e29b6b2/intelmq/bots/experts/certbund_contact/common.py#L26

uses the Python module `enum` which is only available from the standard library Python v>=3.4
and intelmq also support Python 3.3 (see setup.py and CHANGELOG.md)

Possible solutions:
 * convince intelmq to move to Python 3.4
 * add a backport of enum to the requirements (e.g. https://github.com/jstasiak/enum-compat which imports https://pypi.python.org/pypi/enum34/1.1.6 if needed).
 * Change the code to not use enum anymore.

**Comment by wagner-certat** [comment]
> convince intelmq to move to Python 3.4

python 3.3 does receive updates until 2017-09, so if it's not a problem I'd support it till then
